import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { CartProvider } from '@/CartContext';
import { UserProvider } from "@/app/components/UserContext";
import Header from "@/app/components/Header";
import { AuthProvider } from "@/app/AuthProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-Hant">
      <body
        className={`min-h-screen bg-background text-foreground font-sans antialiased ${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning={true}
      >
        <AuthProvider>
          <UserProvider>
            <CartProvider>
              <Header />
              <main className="pt-16 min-h-[calc(100vh-4rem)]">
                {children}
              </main>
              <Toaster position="top-center" toastOptions={{
                style: {
                  background: '#333',
                  color: '#fff',
                  padding: '16px',
                  borderRadius: '10px',
                },
                success: {
                  duration: 3000,
                  iconTheme: {
                    primary: '#10B981',
                    secondary: '#FFFFFF',
                  }
                },
              error: {
                duration: 4000,
                iconTheme: {
                  primary: '#EF4444',
                  secondary: '#FFFFFF',
                },
              },
            }} />
          </CartProvider>
        </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
