import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { CartProvider } from '@/CartContext';
import { UserProvider } from "@/app/components/UserContext";
import Header from "@/app/components/Header";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-Hant">
      <body
        className={`min-h-screen bg-background text-foreground font-sans antialiased ${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning={true}
      >
        <UserProvider>
          <CartProvider>
            <Header />
            <main className="pt-16 min-h-[calc(100vh-4rem)]">
              {children}
            </main>
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
